-- Resource Link
ALTER TABLE HFJ_RES_LINK ALTER COLUMN SRC_PATH TYPE varchar(200);

-- Search
CREATE SEQUENCE SEQ_RES_REINDEX_JOB START 1 INCREMENT 50;

ALTER TABLE HFJ_SEARCH ADD COLUMN OPTLOCK_VERSION int4;
ALTER TABLE HFJ_SEARCH ADD COLUMN SEARCH_DELETED boolean;
ALTER TABLE HFJ_SEARCH ADD COLUMN SEARCH_PARAM_MAP oid;

CREATE TABLE HFJ_RES_REINDEX_JOB (
  PID int8 NOT NULL,
  JOB_DELETED boolean NOT NULL,
  RES_TYPE varchar(255),
  SUSPENDED_UNTIL timestamp,
  UPDATE_THRESHOLD_HIGH timestamp NOT NULL,
  UPDATE_THRESHOLD_LOW timestamp,
  REINDEX_COUNT int4,
  PRIMARY KEY (PID)
);
