-- Forced ID changes
DROP INDEX IDX_FORCEDID_TYPE_FORCEDID;
ALTER TABLE HFJ_FORCED_ID DROP CONSTRAINT IDX_FORCEDID_TYPE_RESID;

CREATE UNIQUE INDEX IDX_FORCEDID_TYPE_FID ON HFJ_FORCED_ID(RESOURCE_TYPE, FORCED_ID);

-- Indexes - Coords
ALTER TABLE HFJ_SPIDX_COORDS ADD COLUMN HASH_IDENTITY int8;

DROP INDEX IDX_SP_COORDS;

CREATE INDEX IDX_SP_COORDS_HASH ON HFJ_SPIDX_COORDS(HASH_IDENTITY, SP_LATITUDE, SP_LONGITUDE);

-- Indexes - Date
ALTER TABLE HFJ_SPIDX_DATE ADD COLUMN HASH_IDENTITY int8;

CREATE INDEX IDX_SP_DATE_HASH ON HFJ_SPIDX_DATE(HASH_IDENTITY, SP_VALUE_LOW, SP_VALUE_HIGH);

-- Indexes - Number
ALTER TABLE HFJ_SPIDX_NUMBER ADD COLUMN HASH_IDENTITY int8;

DROP INDEX IDX_SP_NUMBER;

CREATE INDEX IDX_SP_NUMBER_HASH_VAL ON HFJ_SPIDX_NUMBER(HASH_IDENTITY, SP_VALUE);

-- Indexes - Quantity
ALTER TABLE HFJ_SPIDX_QUANTITY ADD COLUMN HASH_IDENTITY int8;
ALTER TABLE HFJ_SPIDX_QUANTITY ADD COLUMN HASH_IDENTITY_SYS_UNITS int8;
ALTER TABLE HFJ_SPIDX_QUANTITY ADD COLUMN HASH_IDENTITY_AND_UNITS int8;

DROP INDEX IDX_SP_QUANTITY;

CREATE INDEX IDX_SP_QUANTITY_HASH ON HFJ_SPIDX_QUANTITY(HASH_IDENTITY, SP_VALUE);
CREATE INDEX IDX_SP_QUANTITY_HASH_UN ON HFJ_SPIDX_QUANTITY(HASH_IDENTITY_AND_UNITS, SP_VALUE);
CREATE INDEX IDX_SP_QUANTITY_HASH_SYSUN ON HFJ_SPIDX_QUANTITY(HASH_IDENTITY_SYS_UNITS, SP_VALUE);

-- Indexes - String
ALTER TABLE HFJ_SPIDX_STRING ADD COLUMN HASH_IDENTITY int8;

DROP INDEX IDX_SP_STRING;

CREATE INDEX IDX_SP_STRING_HASH_NRM ON HFJ_SPIDX_STRING(HASH_NORM_PREFIX, SP_VALUE_NORMALIZED);
CREATE INDEX IDX_SP_STRING_HASH_EXCT ON HFJ_SPIDX_STRING(HASH_EXACT);

-- Indexes - Token
ALTER TABLE HFJ_SPIDX_TOKEN ADD COLUMN HASH_IDENTITY int8;

DROP INDEX IDX_SP_TOKEN;
DROP INDEX IDX_SP_TOKEN_UNQUAL;

CREATE INDEX IDX_SP_TOKEN_HASH ON HFJ_SPIDX_TOKEN(HASH_IDENTITY);
CREATE INDEX IDX_SP_TOKEN_HASH_S ON HFJ_SPIDX_TOKEN(HASH_SYS);
CREATE INDEX IDX_SP_TOKEN_HASH_SV ON HFJ_SPIDX_TOKEN(HASH_SYS_AND_VALUE);
CREATE INDEX IDX_SP_TOKEN_HASH_V ON HFJ_SPIDX_TOKEN(HASH_VALUE);

-- Indexes - URI
ALTER TABLE HFJ_SPIDX_URI ADD COLUMN HASH_IDENTITY int8;

CREATE INDEX IDX_SP_URI_HASH_IDENTITY ON HFJ_SPIDX_URI(HASH_IDENTITY, SP_URI);
CREATE INDEX IDX_SP_URI_HASH_URI ON HFJ_SPIDX_URI(HASH_URI);

-- Search Parameter Presence
ALTER TABLE HFJ_RES_PARAM_PRESENT DROP CONSTRAINT IDX_RESPARMPRESENT_SPID_RESID;

ALTER TABLE HFJ_RES_PARAM_PRESENT ADD COLUMN HASH_PRESENCE int8;

CREATE INDEX IDX_RESPARMPRESENT_HASHPRES ON HFJ_RES_PARAM_PRESENT(HASH_PRESENCE);

-- Concept
ALTER TABLE TRM_CONCEPT ADD COLUMN CONCEPT_UPDATED timestamp;
ALTER TABLE TRM_CONCEPT ADD COLUMN PARENT_PIDS text;
ALTER TABLE TRM_CONCEPT ALTER COLUMN CODE TYPE varchar(500);

CREATE INDEX IDX_CONCEPT_UPDATED ON TRM_CONCEPT(CONCEPT_UPDATED);

-- Concept Designation
ALTER TABLE TRM_CONCEPT_DESIG ADD COLUMN CS_VER_PID int8;

ALTER TABLE TRM_CONCEPT_DESIG ADD CONSTRAINT FK_CONCEPTDESIG_CSV FOREIGN KEY (CS_VER_PID) REFERENCES TRM_CODESYSTEM_VER;

-- Concept Property
ALTER TABLE TRM_CONCEPT_PROPERTY ADD COLUMN CS_VER_PID int8;

ALTER TABLE TRM_CONCEPT_PROPERTY ADD CONSTRAINT FK_CONCEPTPROP_CSV FOREIGN KEY (CS_VER_PID) REFERENCES TRM_CODESYSTEM_VER;
