-- Table: HFJ_BINARY_STORAGE_BLOB
CREATE TABLE HFJ_BINARY_STORAGE_BLOB ( BLOB_ID varchar(200)  not null, RESOURCE_ID varchar(100)  not null, BLOB_SIZE int4 , CONTENT_TYPE varchar(100)  not null, BLOB_DATA oid  not null, PUBLISHED_DATE timestamp  not null, BLOB_HASH varchar(128) ,  PRIMARY KEY (BLOB_ID) ) ;


-- Table: TRM_CONCEPT_MAP_GROUP
ALTER TABLE TRM_CONCEPT_MAP_GROUP RENAME COLUMN myConceptMapUrl TO CONCEPT_MAP_URL;
ALTER TABLE TRM_CONCEPT_MAP_GROUP RENAME COLUMN mySourceValueSet TO SOURCE_VS;
ALTER TABLE TRM_CONCEPT_MAP_GROUP RENAME COLUMN myTargetValueSet TO TARGET_VS;
alter table TRM_CONCEPT_MAP_GROUP alter column SOURCE_VERSION type varchar(200);
alter table TRM_CONCEPT_MAP_GROUP alter column TARGET_VERSION type varchar(200);


-- Table: TRM_CONCEPT_MAP_GRP_ELEMENT
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELEMENT RENAME COLUMN myConceptMapUrl TO CONCEPT_MAP_URL;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELEMENT RENAME COLUMN mySystem TO SYSTEM_URL;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELEMENT RENAME COLUMN mySystemVersion TO SYSTEM_VERSION;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELEMENT RENAME COLUMN myValueSet TO VALUESET_URL;
alter table TRM_CONCEPT_MAP_GRP_ELEMENT alter column SOURCE_CODE type varchar(500);


-- Table: TRM_CONCEPT_MAP_GRP_ELM_TGT
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELM_TGT RENAME COLUMN myConceptMapUrl TO CONCEPT_MAP_URL;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELM_TGT RENAME COLUMN mySystem TO SYSTEM_URL;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELM_TGT RENAME COLUMN mySystemVersion TO SYSTEM_VERSION;
ALTER TABLE TRM_CONCEPT_MAP_GRP_ELM_TGT RENAME COLUMN myValueSet TO VALUESET_URL;
alter table TRM_CONCEPT_MAP_GRP_ELM_TGT alter column TARGET_CODE type varchar(500);


-- Table: TRM_CONCEPT
ALTER TABLE TRM_CONCEPT RENAME COLUMN CODE TO CODEVAL;


-- Table: SEQ_VALUESET_PID
create sequence SEQ_VALUESET_PID start 1 increment 50;


-- Table: TRM_VALUESET
CREATE TABLE TRM_VALUESET ( PID int8  not null, URL varchar(200)  not null, RES_ID int8  not null, VSNAME varchar(200) ,  PRIMARY KEY (PID) ) ;
create unique index IDX_VALUESET_URL on TRM_VALUESET(URL);
alter table TRM_VALUESET add constraint FK_TRMVALUESET_RES foreign key (RES_ID) references HFJ_RESOURCE;
alter table TRM_VALUESET add column EXPANSION_STATUS varchar(50)  not null;
create index IDX_VALUESET_EXP_STATUS on TRM_VALUESET(EXPANSION_STATUS);


-- Table: SEQ_VALUESET_CONCEPT_PID
create sequence SEQ_VALUESET_CONCEPT_PID start 1 increment 50;


-- Table: TRM_VALUESET_CONCEPT
CREATE TABLE TRM_VALUESET_CONCEPT ( PID int8  not null, VALUESET_PID int8  not null, SYSTEM_URL varchar(200)  not null, CODEVAL varchar(500)  not null, DISPLAY varchar(400) ,  PRIMARY KEY (PID) ) ;
alter table TRM_VALUESET_CONCEPT add constraint FK_TRM_VALUESET_PID foreign key (VALUESET_PID) references TRM_VALUESET;
create unique index IDX_VS_CONCEPT_CS_CD on TRM_VALUESET_CONCEPT(VALUESET_PID, SYSTEM_URL, CODEVAL);


-- Table: SEQ_VALUESET_C_DSGNTN_PID
create sequence SEQ_VALUESET_C_DSGNTN_PID start 1 increment 50;


-- Table: TRM_VALUESET_C_DESIGNATION
CREATE TABLE TRM_VALUESET_C_DESIGNATION ( PID int8  not null, VALUESET_CONCEPT_PID int8  not null, LANG varchar(500) , USE_SYSTEM varchar(500) , USE_CODE varchar(500) , USE_DISPLAY varchar(500) , VAL varchar(500)  not null,  PRIMARY KEY (PID) ) ;
alter table TRM_VALUESET_C_DESIGNATION add constraint FK_TRM_VALUESET_CONCEPT_PID foreign key (VALUESET_CONCEPT_PID) references TRM_VALUESET_CONCEPT;
create index IDX_VALUESET_C_DSGNTN_VAL on TRM_VALUESET_C_DESIGNATION(VAL);


-- Table: TRM_CODESYSTEM_VER
alter table TRM_CODESYSTEM_VER add column CS_DISPLAY varchar(200) ;


-- Table: HFJ_SEARCH
alter table HFJ_SEARCH alter column SEARCH_LAST_RETURNED type timestamp;
alter table HFJ_SEARCH alter column SEARCH_LAST_RETURNED set not null;


-- Table: HFJ_SEARCH_PARM
alter table HFJ_SEARCH_PARM drop constraint if exists IDX_SEARCHPARM_RESTYPE_SPNAME cascade;
drop index if exists IDX_SEARCHPARM_RESTYPE_SPNAME cascade;
alter table HFJ_SEARCH_PARM drop constraint if exists HFJ_SEARCH_PARM_PKEY cascade;
drop index if exists HFJ_SEARCH_PARM_PKEY cascade;
DROP TABLE HFJ_SEARCH_PARM;


-- Table: HFJ_SPIDX_STRING
create index IDX_SP_STRING_HASH_IDENT on HFJ_SPIDX_STRING(HASH_IDENTITY);


-- Table: HFJ_SPIDX_QUANTITY
alter table HFJ_SPIDX_QUANTITY drop column HASH_UNITS_AND_VALPREFIX;
alter table HFJ_SPIDX_QUANTITY drop column HASH_VALPREFIX;
